// future updates - fetch from api instead of hardcoding
export const BRANDS = [
    "Kellogg's",
    "Post",
    "Cheerios",
    "Kashi",
    "Froot Loops",
    "Cinnamon Toast Crunch",
    "Lucky Charms",
    "Golden Grahams",
    "Cap'n Crunch",
    "Cookie Crisp",
    "Great Value",
    "Quaker",
    "Life",
    "Nature Valley",
    "Malt-O-Meal",
    "Total",
    "Fiber One",
    "Reese's",
    "Cocoa Puffs",
    "KixBerry",
    "All-Bran",
    "Trix",
    "Honey Bunches of Oats",
    "Kix",
    "Apple Jacks",
    "Special K",
    "Arrowhead Mills",
    "Bear Naked",
    "Cascadian Farm",
    "Honey Comb",
    ]
